/** @type {import('cz-git').UserConfig} */

module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'upd',
        'feat',
        'fix',
        'refactor',
        'docs',
        'chore',
        'style',
        'revert',
        'ci',
        'ui',
        'build',
        'merge',
        'perf',
      ],
    ],
    'type-case': [0],
    'type-empty': [0],
    'scope-empty': [0],
    'scope-case': [0],
    'subject-full-stop': [0, 'never'],
    'subject-case': [0, 'never'],
    'header-max-length': [0, 'always', 72],
  },
  prompt: {
    alias: { fd: 'docs: fix typos' },
    messages: {
      type: '选择你要提交的类型 :',
      scope: '选择一个提交范围（可选）:',
      customScope: '请输入自定义的提交范围 :',
      subject: '填写简短精炼的变更描述 :\n',
      body: '填写更加详细的变更描述（可选）。使用 "|" 换行 :\n',
      breaking: '列举非兼容性重大的变更（可选）。使用 "|" 换行 :\n',
      footerPrefixesSelect: '选择关联issue前缀（可选）:',
      customFooterPrefix: '输入自定义issue前缀 :',
      footer: '列举关联issue (可选) 例如: #31, #I3244 :\n',
      confirmCommit: '是否提交或修改commit ?',
    },
    types: [
      {
        value: 'feat',
        label: '🎉 新功能',
        name: 'feat:     🎉  A new feature',
        emoji: '🎉',
      },
      {
        value: 'fix',
        label: '🐛 Bug 修复',
        name: 'fix:      🐛  A bug fix',
        emoji: '🐛',
      },
      {
        value: 'ui',
        label: '🎨 视图变更',
        name: 'ui:       🎨   pages ui update',
        emoji: '🎨',
      },
      {
        value: 'docs',
        label: '📝 文档修改',
        name: 'docs:     📝  Documentation only changes',
        emoji: '📝',
      },
      {
        value: 'style',
        label: '💄 风格变更',
        name: 'style:    💄  Changes that do not affect the meaning of the code',
        emoji: '💄',
      },
      {
        value: 'refactor',
        label: '♻️ 重构代码',
        name: 'refactor: ♻️   A code change that neither fixes a bug nor adds a feature',
        emoji: '♻️',
      },
      {
        value: 'perf',
        label: '⚡ 性能优化',
        name: 'perf:     ⚡️  A code change that improves performance',
        emoji: '⚡️',
      },
      {
        value: 'test',
        label: '✅ 测试用例',
        name: 'test:     ✅  Adding missing tests or correcting existing tests',
        emoji: '✅',
      },
      {
        value: 'build',
        label: '📦 打包部署',
        name: 'build:    📦️   Changes that affect the build system or external dependencies',
        emoji: '📦️',
      },
      {
        value: 'ci',
        label: '🚀 自动化',
        name: 'ci:       🚀  Changes to our CI configuration files and scripts',
        emoji: '🚀',
      },
      {
        value: 'chore',
        label: '🔨 辅助工具',
        name: "chore:    🔨  Other changes that don't modify src or test files",
        emoji: '🔨',
      },
      {
        value: 'revert',
        label: '⏪ 回滚功能或版本',
        name: 'revert:   ⏪️  Reverts a previous commit',
        emoji: '⏪️',
      },
      {
        value: 'merge',
        label: '🔀 合并代码',
        name: 'merge:     🔀  merge code',
        emoji: '🔀',
      },
      {
        value: 'upd',
        label: '⬆️ 更新代码',
        name: 'upd:      ⬆️  update something code',
        emoji: '⬆️',
      },
    ],
    useEmoji: true,
    emojiAlign: 'center',
    useAI: false,
    aiNumber: 1,
    themeColorCode: '',
    scopes: [],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: 'bottom',
    customScopesAlias: 'custom',
    emptyScopesAlias: 'empty',
    upperCaseSubject: false,
    markBreakingChangeMode: true,
    allowBreakingChanges: ['feat', 'fix', 'ui', 'revert', 'perf'],
    breaklineNumber: 100,
    breaklineChar: '|',
    skipQuestions: [],
    issuePrefixes: [
      { value: 'fixed', name: 'fixed:      标记 ISSUES 已修复' },
      { value: 'closed', name: 'closed:   标记 ISSUES 已完成' },
      { value: 'resolved', name: 'resolved:   标记 ISSUES 已解决' },
    ],
    customIssuePrefixAlign: 'top',
    emptyIssuePrefixAlias: 'skip',
    customIssuePrefixAlias: 'custom',
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    maxHeaderLength: Infinity,
    maxSubjectLength: Infinity,
    minSubjectLength: 0,
    scopeOverrides: undefined,
    defaultBody: '',
    defaultIssues: '',
    defaultScope: '',
    defaultSubject: '',
  },
};
