/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CopyCodeButton: (typeof import('./src/components/CopyCodeButton.vue'))['default'];
    Demo: (typeof import('./src/components/Demo.vue'))['default'];
    EditOnGithubButton: (typeof import('./src/components/EditOnGithubButton.vue'))['default'];
    EditOnGithubHeader: (typeof import('./src/components/EditOnGithubHeader.vue'))['default'];
    NAutoComplete: (typeof import('naive-ui'))['NAutoComplete'];
    NButton: (typeof import('naive-ui'))['NButton'];
    NCard: (typeof import('naive-ui'))['NCard'];
    NCode: (typeof import('naive-ui'))['NCode'];
    NDialogProvider: (typeof import('naive-ui'))['NDialogProvider'];
    NDivider: (typeof import('naive-ui'))['NDivider'];
    NEl: (typeof import('naive-ui'))['NEl'];
    NGlobalStyle: (typeof import('naive-ui'))['NGlobalStyle'];
    NH1: (typeof import('naive-ui'))['NH1'];
    NIcon: (typeof import('naive-ui'))['NIcon'];
    NLayout: (typeof import('naive-ui'))['NLayout'];
    NLayoutFooter: (typeof import('naive-ui'))['NLayoutFooter'];
    NLayoutHeader: (typeof import('naive-ui'))['NLayoutHeader'];
    NLoadingBarProvider: (typeof import('naive-ui'))['NLoadingBarProvider'];
    NMenu: (typeof import('naive-ui'))['NMenu'];
    NMessageProvider: (typeof import('naive-ui'))['NMessageProvider'];
    NNotificationProvider: (typeof import('naive-ui'))['NNotificationProvider'];
    NP: (typeof import('naive-ui'))['NP'];
    NPopover: (typeof import('naive-ui'))['NPopover'];
    NScrollbar: (typeof import('naive-ui'))['NScrollbar'];
    NTab: (typeof import('naive-ui'))['NTab'];
    NTabs: (typeof import('naive-ui'))['NTabs'];
    NText: (typeof import('naive-ui'))['NText'];
    NThemeEditor: (typeof import('naive-ui'))['NThemeEditor'];
    NTooltip: (typeof import('naive-ui'))['NTooltip'];
  }
}
