/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CopyCodeButton: (typeof import('./src/components/CopyCodeButton.vue'))['default'];
    Demo: (typeof import('./src/components/Demo.vue'))['default'];
    EditOnGithubButton: (typeof import('./src/components/EditOnGithubButton.vue'))['default'];
    EditOnGithubHeader: (typeof import('./src/components/EditOnGithubHeader.vue'))['default'];
    ProLayout: (typeof import('naive-ui-pro'))['ProLayout'];
  }
}
